language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - 7

sudo: false

matrix:
  allow_failures:
    - php: 7

install: travis_retry composer install --no-interaction --prefer-source

script: php vendor/bin/phpspec run -fpretty
